"""
Django settings for Tienda project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""
import os
from dotenv import load_dotenv
from pathlib import Path



load_dotenv()  # Esta línea carga las variables del archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Tus aplicaciones personalizadas
    'usuarios',
    'productos',
    'afiliados',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Para Google OAuth
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # ✅ CSRF activado
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Agrega ESTE middleware de allauth:
    'allauth.account.middleware.AccountMiddleware',  # ← ¡NECESARIO!
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tienda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tienda.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es-es'  # ✅ Cambiado a español
TIME_ZONE = 'America/Asuncion'  # ✅ Zona horaria de Paraguay
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # ← NUEVA LÍNEA

# Media files (Archivos subidos por usuarios)  # ← NUEVA SECCIÓN
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ CONFIGURACIONES PERSONALIZADAS CRÍTICAS
AUTH_USER_MODEL = 'usuarios.CustomUser'  # Modelo de usuario personalizado

# ✅ Configuración CSRF para desarrollo
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False  # Cambiar a True en producción con HTTPS
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']

# ✅ Configuración de cookies para desarrollo
SESSION_COOKIE_SECURE = False  # True en producción
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# ✅ Para evitar problemas de cache en desarrollo
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 semanas en segundos

# ✅ Configuración para @login_required - ¡CORREGIDO!
LOGIN_URL = '/login/'  # ← CAMBIO IMPORTANTE: antes era '/usuarios/login/'
LOGIN_REDIRECT_URL = '/productos/mis-productos/'  # Redirige a "Mis Productos" tras login

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  # Saltar vista simple y mostrar selector de cuentas
        },
        'OAUTH_PKCE_ENABLED': True,
        'FETCH_USERINFO': True,
    }
}

# Configuraciones adicionales para mejor UX (agregar después de SOCIALACCOUNT_PROVIDERS)
SOCIALACCOUNT_LOGIN_ON_GET = True  # Login automático al callback de Google
SOCIALACCOUNT_AUTO_SIGNUP = True   # No mostrar formulario adicional de registro
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Evitar paso extra de verificación de email