# Generated by Django 5.2.5 on 2025-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('FISICO', 'Fisico'), ('DIGITAL', 'Digital')], default='FISICO', max_length=10),
        ),
    ]
