# Generated by Django 5.2.5 on 2025-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comisiones_ganadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisiones Totales Ganadas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_upgrade_vendedor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Upgrade a Vendedor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='puede_crear_productos',
            field=models.BooleanField(default=False, verbose_name='Puede Crear Productos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('COMPRADOR', 'Comprador'), ('VENDEDOR', 'Vendedor/Afiliado')], default='COMPRADOR', max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
