# Generated by Django 5.2.5 on 2025-11-18 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_comisiones_ganadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='afiliado_referido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_referido',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se registró vía link de afiliado', null=True, verbose_name='Fecha de Referido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='origen_registro',
            field=models.CharField(choices=[('DIRECTO', 'Registro directo'), ('AFILIADO', 'Vía link de afiliado'), ('GOOGLE', 'Google OAuth'), ('ADMIN', 'Creado por admin')], default='DIRECTO', max_length=10, verbose_name='Origen de Registro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_referidos', to=settings.AUTH_USER_MODEL, verbose_name='Referido por'),
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
