# Generated by Django 5.2.5 on 2025-09-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_producto_tipo_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
