# Generated by Django 5.2.5 on 2025-11-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_pedido_afiliado_referido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='areas_interes',
            field=models.TextField(blank=True, help_text='¿Qué tipo de productos te interesa promocionar? (opcional)', verbose_name='Áreas de Interés'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='biografia_afiliado',
            field=models.TextField(blank=True, help_text='Cuéntanos sobre ti y por qué quieres ser afiliado (opcional)', verbose_name='Biografía/Presentación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='canales_promocion',
            field=models.TextField(blank=True, help_text='¿Dónde planeas promocionar? (redes sociales, blog, email, etc.) - opcional', verbose_name='Canales de Promoción'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='datos_afiliacion_completos',
            field=models.BooleanField(default=False, help_text='Indica si completó los datos mínimos para poder afiliarse a productos', verbose_name='Datos de Afiliación Completos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experiencia_marketing',
            field=models.TextField(blank=True, help_text='Describe tu experiencia previa en marketing digital o ventas (opcional)', verbose_name='Experiencia en Marketing'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_completado_perfil',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado Perfil Afiliación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='País de Residencia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('fisica', 'Persona Física'), ('juridica', 'Persona Jurídica')], max_length=20, verbose_name='Tipo de Persona'),
        ),
    ]
