# Generated by Django 5.2.5 on 2025-11-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customuser_areas_interes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Banco'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='datos_retiro_completos',
            field=models.BooleanField(default=False, verbose_name='Datos de Retiro Completos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_ultimo_retiro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Retiro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_titular_billetera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Titular'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_celular_retiro',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular para Retiro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='retiro_minimo',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=8, verbose_name='Retiro Mínimo (Gs)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='retiros_pendientes',
            field=models.BooleanField(default=False, verbose_name='Tiene Retiros Pendientes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible para Retiro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saldo_retirado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Retirado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_retiro',
            field=models.CharField(blank=True, choices=[('banco', 'Transferencia Bancaria'), ('tigo_money', 'Tigo Money'), ('personal_pay', 'Personal Pay'), ('weepay', 'WeePayy')], max_length=20, verbose_name='Método de Retiro Preferido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titular de la Cuenta'),
        ),
    ]
