# Generated by Django 5.2.5 on 2025-11-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_public_key', models.CharField(blank=True, max_length=200, verbose_name='Public Key de Mercado Pago')),
                ('mercadopago_access_token', models.CharField(blank=True, max_length=200, verbose_name='Access Token de Mercado Pago')),
                ('comision_afiliado_default', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Comisión por defecto para afiliados')),
                ('banco_nombre', models.CharField(blank=True, max_length=100)),
                ('banco_cuenta', models.CharField(blank=True, max_length=50)),
                ('banco_titular', models.CharField(blank=True, max_length=200)),
                ('banco_cedula', models.CharField(blank=True, max_length=20)),
                ('requiere_direccion_digital', models.BooleanField(default=False, verbose_name='Requerir dirección para productos digitales')),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuración de Pagos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregado')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('PROCESANDO', 'En Proceso'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion_envio', models.TextField(blank=True, verbose_name='Dirección de entrega')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('metodo_pago', models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('CONTRA_ENTREGA', 'Pago en Puerta'), ('TARJETA', 'Tarjeta de Crédito/Débito')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('comprobante_pago', models.ImageField(blank=True, help_text='Imagen del comprobante de transferencia', null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago')),
                ('comision_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión total')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% de comisión')),
                ('comision_pagada', models.BooleanField(default=False, verbose_name='Comisión pagada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Sube una imagen del producto', null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('tipo_producto', models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], default='FISICO', max_length=7, verbose_name='Tipo de Producto')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en inventario. Los productos digitales tienen stock ilimitado', verbose_name='Stock Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
