# Generated by Django 5.2.5 on 2025-09-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen')),
                ('tipo_producto', models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], default='FISICO', max_length=7, verbose_name='Tipo de Producto')),
            ],
        ),
    ]
