# Generated by Django 5.2.5 on 2025-10-02 18:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_public_key', models.CharField(blank=True, max_length=200, verbose_name='Public Key de Mercado Pago')),
                ('mercadopago_access_token', models.CharField(blank=True, max_length=200, verbose_name='Access Token de Mercado Pago')),
                ('comision_afiliado_default', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Comisión por defecto para afiliados')),
                ('banco_nombre', models.CharField(blank=True, max_length=100)),
                ('banco_cuenta', models.CharField(blank=True, max_length=50)),
                ('banco_titular', models.CharField(blank=True, max_length=200)),
                ('banco_cedula', models.CharField(blank=True, max_length=20)),
                ('requiere_direccion_digital', models.BooleanField(default=False, verbose_name='Requerir dirección para productos digitales')),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuración de Pagos',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Producto Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='afiliados',
            field=models.ManyToManyField(blank=True, related_name='productos_afiliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 2, 18, 42, 18, 772479, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, help_text='Cantidad disponible en inventario. Los productos digitales tienen stock ilimitado', verbose_name='Stock Disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen del producto', null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Ej: juan-perez → tutienda.com/vendedor/juan-perez', unique=True, verbose_name='URL Personalizada')),
                ('nombre_tienda', models.CharField(default='Mi Tienda', max_length=100, verbose_name='Nombre de la Tienda')),
                ('descripcion', models.TextField(default='¡Bienvenido a mi tienda!', help_text='Cuéntale a tus clientes sobre ti', verbose_name='Descripción')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='vendedores/perfiles/', verbose_name='Foto de Perfil')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vendedores/banners/', verbose_name='Banner de Portada')),
                ('whatsapp', models.CharField(blank=True, help_text='Ej: +5491123456789', max_length=20, verbose_name='WhatsApp')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, help_text='Solo el nombre de usuario (sin @)', max_length=50, verbose_name='Instagram')),
                ('color_tema', models.CharField(default='#667eea', help_text='Color principal de tu página', max_length=7, verbose_name='Color del Tema')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Vendedor',
                'verbose_name_plural': 'Perfiles de Vendedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('PROCESANDO', 'En Proceso'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion_envio', models.TextField(blank=True, verbose_name='Dirección de entrega')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('codigo_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de referencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vendedor_referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_referidas', to='productos.perfilvendedor', verbose_name='Vendedor referido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ProductoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.TextField(help_text='Escribe tu propia descripción de venta', verbose_name='Tu Descripción del Producto')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Puede incluir tu ganancia/comisión', max_digits=10, verbose_name='Tu Precio de Venta')),
                ('mensaje_especial', models.TextField(blank=True, help_text='¿Por qué deberían comprarte a ti?', verbose_name='Mensaje Especial')),
                ('beneficios_extra', models.TextField(blank=True, help_text='Lista de beneficios que ofreces', verbose_name='Beneficios Adicionales')),
                ('vistas', models.IntegerField(default=0, verbose_name='Número de Vistas')),
                ('clicks_whatsapp', models.IntegerField(default=0, verbose_name='Clicks en WhatsApp')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicación Activa')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores_promocionando', to='productos.producto', verbose_name='Producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_promocionados', to='productos.perfilvendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Producto Promocionado',
                'verbose_name_plural': 'Productos Promocionados',
                'ordering': ['-fecha_publicacion'],
                'unique_together': {('vendedor', 'producto')},
            },
        ),
    ]
