# Generated by Django 5.2.5 on 2025-09-07 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='afiliados',
            field=models.ManyToManyField(blank=True, related_name='productos_afiliados', to=settings.AUTH_USER_MODEL),
        ),
    ]
