# Generated by Django 5.2.5 on 2025-11-15 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='afiliado_referido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_como_afiliado', to=settings.AUTH_USER_MODEL, verbose_name='Afiliado que refirió'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='afiliados',
            field=models.ManyToManyField(blank=True, related_name='productos_afiliados', to=settings.AUTH_USER_MODEL, verbose_name='Afiliados'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
