# Generated by Django 5.2.5 on 2025-10-03 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_configuracionpagos_alter_producto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovendedor',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor_referido',
        ),
        migrations.RemoveField(
            model_name='productovendedor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo_referencia',
        ),
        migrations.AddField(
            model_name='pedido',
            name='afiliado_referido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_como_afiliado', to=settings.AUTH_USER_MODEL, verbose_name='Afiliado que refirió'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comision_pagada',
            field=models.BooleanField(default=False, verbose_name='Comisión pagada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comision_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión total'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% de comisión'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='afiliados',
            field=models.ManyToManyField(blank=True, related_name='productos_afiliados', to=settings.AUTH_USER_MODEL, verbose_name='Afiliados'),
        ),
        migrations.DeleteModel(
            name='PerfilVendedor',
        ),
        migrations.DeleteModel(
            name='ProductoVendedor',
        ),
    ]
