# Generated by Django 5.2.5 on 2025-11-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comision_total',
        ),
    ]
