# Generated by Django 5.2.5 on 2025-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_pedido_comision_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comision_total_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión total'),
        ),
    ]
