# Generated by Django 5.2.5 on 2025-10-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_productovendedor_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante de transferencia', null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago'),
        ),
    ]
