# Generated by Django 5.2.5 on 2025-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pedido_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('CONTRA_ENTREGA', 'Pago en Puerta'), ('TARJETA', 'Tarjeta de Crédito/Débito')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
    ]
