# Generated by Django 5.2.5 on 2025-09-29 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_options_producto_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Ej: juan-perez → tutienda.com/vendedor/juan-perez', unique=True, verbose_name='URL Personalizada')),
                ('nombre_tienda', models.CharField(default='Mi Tienda', max_length=100, verbose_name='Nombre de la Tienda')),
                ('descripcion', models.TextField(default='¡Bienvenido a mi tienda!', help_text='Cuéntale a tus clientes sobre ti', verbose_name='Descripción')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='vendedores/perfiles/', verbose_name='Foto de Perfil')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vendedores/banners/', verbose_name='Banner de Portada')),
                ('whatsapp', models.CharField(blank=True, help_text='Ej: +5491123456789', max_length=20, verbose_name='WhatsApp')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, help_text='Solo el nombre de usuario (sin @)', max_length=50, verbose_name='Instagram')),
                ('color_tema', models.CharField(default='#667eea', help_text='Color principal de tu página', max_length=7, verbose_name='Color del Tema')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Vendedor',
                'verbose_name_plural': 'Perfiles de Vendedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.TextField(help_text='Escribe tu propia descripción de venta', verbose_name='Tu Descripción del Producto')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Puede incluir tu ganancia/comisión', max_digits=10, verbose_name='Tu Precio de Venta')),
                ('mensaje_especial', models.TextField(blank=True, help_text='¿Por qué deberían comprarte a ti? Ej: Envío gratis, garantía extendida, etc.', verbose_name='Mensaje Especial')),
                ('beneficios_extra', models.TextField(blank=True, help_text='Lista de beneficios que ofreces (separados por líneas)', verbose_name='Beneficios Adicionales')),
                ('vistas', models.IntegerField(default=0, help_text='Cuántas personas visitaron esta página', verbose_name='Número de Vistas')),
                ('clicks_whatsapp', models.IntegerField(default=0, help_text='Cuántas veces clickearon tu WhatsApp', verbose_name='Clicks en WhatsApp')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicación Activa')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores_promocionando', to='productos.producto', verbose_name='Producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_promocionados', to='productos.perfilvendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Producto Promocionado',
                'verbose_name_plural': 'Productos Promocionados',
                'ordering': ['-fecha_publicacion'],
                'unique_together': {('vendedor', 'producto')},
            },
        ),
    ]
