# Generated by Django 5.2.5 on 2025-10-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_perfilvendedor_productovendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_public_key', models.CharField(blank=True, max_length=200, verbose_name='Public Key de Mercado Pago')),
                ('mercadopago_access_token', models.CharField(blank=True, max_length=200, verbose_name='Access Token de Mercado Pago')),
                ('comision_afiliado_default', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Comisión por defecto para afiliados')),
                ('banco_nombre', models.CharField(blank=True, max_length=100)),
                ('banco_cuenta', models.CharField(blank=True, max_length=50)),
                ('banco_titular', models.CharField(blank=True, max_length=200)),
                ('banco_cedula', models.CharField(blank=True, max_length=20)),
                ('requiere_direccion_digital', models.BooleanField(default=False, verbose_name='Requerir dirección para productos digitales')),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuración de Pagos',
            },
        ),
        migrations.AlterField(
            model_name='productovendedor',
            name='beneficios_extra',
            field=models.TextField(blank=True, help_text='Lista de beneficios que ofreces', verbose_name='Beneficios Adicionales'),
        ),
        migrations.AlterField(
            model_name='productovendedor',
            name='clicks_whatsapp',
            field=models.IntegerField(default=0, verbose_name='Clicks en WhatsApp'),
        ),
        migrations.AlterField(
            model_name='productovendedor',
            name='mensaje_especial',
            field=models.TextField(blank=True, help_text='¿Por qué deberían comprarte a ti?', verbose_name='Mensaje Especial'),
        ),
        migrations.AlterField(
            model_name='productovendedor',
            name='vistas',
            field=models.IntegerField(default=0, verbose_name='Número de Vistas'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado'), ('PROCESANDO', 'En Proceso'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion_entrega', models.TextField(blank=True, verbose_name='Dirección de entrega')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('metodo_pago', models.CharField(choices=[('CONTRA_ENTREGA', 'Pago contra entrega'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('TARJETA', 'Tarjeta de crédito/débito')], max_length=20)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago')),
                ('codigo_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de referencia del afiliado')),
                ('comision_afiliado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión del afiliado')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% de comisión')),
                ('comision_pagada', models.BooleanField(default=False, verbose_name='Comisión pagada')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas administrativas')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='productos.producto')),
                ('vendedor_referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_referidas', to='productos.perfilvendedor', verbose_name='Vendedor que refirió')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
    ]
